name: Deploy to Server

on:
  push:
    branches:
      - main  # 変更がpushされたとき

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOST_SSH_KEY }}

      - name: Sync files to server
        run: |
          rsync -avz --delete ./ nen@163.43.158.178:/var/www/html/
        env:
          RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'

